### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by rsuchecki** [plantinformatics/pretzel-input-generator#17]
E.g. from [here](https://github.com/nextflow-io/rnaseq-nf/blob/modules/.travis.yml)

```yml
sudo: required
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master  
install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install graphviz realpath
script:
- curl -fsSL get.nextflow.io | bash
- ./nextflow run . -with-docker
```
